language: python
python: "3.6"
env:
  global:
  - secure: "j2MbXx+y3Oiwb/03tpp67foapTfoTlS3Cyqu0K+EAGmr8fGHkyv2KVR7jMAjq0c4DDRkqj9lPlsCaGscs52XDTZKG5+c0tS3NOUo/bOINyO3rPfSMa+U1lngBkOicxPeYbmmAHnYK9aBJGrkkq/W0Bj/Y/PEKVDpP3PfIcoFB6kzM4qnwJXgyqqsX+JooodOAfMaw5mxBVAsKOHJ5mw7FR+kYf/OplhSKJFpCv4CFiaFTSMQBH90HhSlOF1IrWfYw2QaWjIETBuo7XhRnloUbgInYrk5nNMbSngc6Un10ExpFeqlkjSpHWf/7dttD/TYoxcVQ54vRexGSdI0hsiggaaXfkfz+GqQSqoYzfjc/ZyJmuA/K5n0o/3z1iJyo9FQw7219OZvwrEIg3+HJ2AQC0P3SV1Np+L/3jP6PSm5T2mDlXv6a6zpioUKQF061xMRwfrF+dM9qlUPLggyqtuygtG/W0OHJW3Frtlkqnh/Wmo4wd287vk3gqzBUm2pSDZy/6UDvwIDaGPKFfJ+rzh3jf+wDj/GUKz3VCzya57ioYng23AbmmeOaU6H7AWUi843sUYyUloc/SR6nxA8zF5oNcyCMkXPrWwiEZiWSWvNStIbtSd/XYoGKS5Bysvf+X0VBTQjUhwdQ6aIyrVtVr8X5C3iHZ12WdblvetH1t3+/oM="
notifications:
  email: rijard.barnes@gmail.com
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- pip install pyOpenSSL ndg-httpsclient pyasn1
- pip install twine wheel
- docker pull $DOCKER_IMAGE
script:
- pwd
- ls
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.ci/travis/build-wheels.sh
- ls wheelhouse/
after_success:
- pwd
- ls
- bash .ci/travis/deploy_to_pypi.sh
# deploy:
#   provider: pypi
#   user: rbarnes
#   password:
#     secure: qvHDwk04g7uuSvG13rMn1HoL5Sl6CRMMnguVvVmOSuyiornPJ+3ezxPm/B7KtNKpDAtpBImlJxEZnBBdlYE8KUZo2Dpqkey1oPTO5+Y9+MaDGjAL4M1umcUj5BxjknpeL/YObToctZcz5VyE6g2H3EZXSZIZLhITcTv3+W7yaEweh6tEjodAlwPV1Wt59IxRZGRCXQ+UFtrOU7vDUEG9sB8KE7DHkklRMXTJHUJAsh2325lLnoTfRsT2uiay52R6SiUPsai6xewYjL9ahOEL6vXSIpKJWTCqLlhWMGOHZ8czd0VhVFYpPX7fKUenxnh4peNsHSunU/Ca0dkvCDI7rBzhDoyq4iiLD6y56ZMtaEP9+WwwLAfhhV7YzLYOC5C01v5jbk0EdzmPZLOfP6NDQSVgpz+0VIBoTybJYwxiabDpNn9KDHHwFFTlQwNtvNDy/sqNZrT2pU/E4BWk5P+6jTNyDlEuwjIPgIT8ycXAGIMe0K8wH02pQWmdVj2dnzQxWqMKqmXMRdD2NLCTNFnpMAEO55HP9ZxzNMwbnJskn4O1yYKFOXw3PsxyGgWL5nkkYrTIrDQtxSW4kWDVMFmfmfhpFD1myrH0gYb30VM4Cbe7jkJx/kBwYuGg5tUSyvFtJyzhNl8PnpnK0YL2pEKB9K/3MBleP7eYplK5+DQN6bw=
#   on:
#     branch: master    
# #  on:
# #    tags: true
#   file: /io/wheelhouse/*
#   skip_cleanup: true
#   overwrite: true
#   python: 3.5
