language: python
python: "3.6"
env:
  global:
  - secure: "JvkGsc9Un5lud0NX0SNTI5mfONnAaMwSCOMETpQwrz/Yb2k7pGoiWzZnNxWyOd1Zzac4DbsudhOy8vNz628JVKnT56tTxjDQLGr3ex07O7YGohjG1iJUcPUo1z+o+gRhr64M0SRq1nVa2CZDf0z8ZWfE6mL6SVQmW34xc/ooissn5Q4sDgjjDsM3sJ/9DmjmDGch7+M+87qP9c4bFQGZzKDIPOaXQQcr+K7Hr/AgaeWS19qDi04DXj5tl5gSwYZwyAsUxJdYwTSA4DprR78y+ilZkXMCwd6FPvSRr+p5KEnqNBRzPZ7Sig+uwI5Y8E6FdyIM53Dy4a2HZs4gxamtMXZMwTkXKwakFoGeebvbV1o3h06l7bHh0h6LymngIjLcyKoR6kqj3bbqc5/f2MqeS+GrObsmTcmCFF5QfjfAfeJekXY2k0/A9AwYX87fi0F3xaIBSg9N1GhwjbvVpE/+TE1ESriTuPTiuUH1JWQKDNQPNJ3bEh3bNYF8t0YrxWzzd9aGEoMCsmaMnnX9/VFbnnJYN4kyCDQjB1t8M76MM9UHjwABCtBbQMvmyy4de+PZsPE0dyY0BjSloj7+eS2o9uiCIOJOd9UAk2rtM//CTu3UTiPQ8h6y78XtWiDWf7gvYKSg6Vkpf+HKc9LydAm+TjszakQW5weMeFcsW1LJMPY="
notifications:
  email: rijard.barnes@gmail.com
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- pip install pyOpenSSL ndg-httpsclient pyasn1
- pip install twine wheel
- docker pull $DOCKER_IMAGE
script:
- pwd
- ls
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.ci/travis/build-wheels.sh
- ls wheelhouse/
after_success:
- pwd
- ls
- bash .ci/travis/deploy_to_pypi.sh
# deploy:
#   provider: pypi
#   user: rbarnes
#   password:
#     secure: qvHDwk04g7uuSvG13rMn1HoL5Sl6CRMMnguVvVmOSuyiornPJ+3ezxPm/B7KtNKpDAtpBImlJxEZnBBdlYE8KUZo2Dpqkey1oPTO5+Y9+MaDGjAL4M1umcUj5BxjknpeL/YObToctZcz5VyE6g2H3EZXSZIZLhITcTv3+W7yaEweh6tEjodAlwPV1Wt59IxRZGRCXQ+UFtrOU7vDUEG9sB8KE7DHkklRMXTJHUJAsh2325lLnoTfRsT2uiay52R6SiUPsai6xewYjL9ahOEL6vXSIpKJWTCqLlhWMGOHZ8czd0VhVFYpPX7fKUenxnh4peNsHSunU/Ca0dkvCDI7rBzhDoyq4iiLD6y56ZMtaEP9+WwwLAfhhV7YzLYOC5C01v5jbk0EdzmPZLOfP6NDQSVgpz+0VIBoTybJYwxiabDpNn9KDHHwFFTlQwNtvNDy/sqNZrT2pU/E4BWk5P+6jTNyDlEuwjIPgIT8ycXAGIMe0K8wH02pQWmdVj2dnzQxWqMKqmXMRdD2NLCTNFnpMAEO55HP9ZxzNMwbnJskn4O1yYKFOXw3PsxyGgWL5nkkYrTIrDQtxSW4kWDVMFmfmfhpFD1myrH0gYb30VM4Cbe7jkJx/kBwYuGg5tUSyvFtJyzhNl8PnpnK0YL2pEKB9K/3MBleP7eYplK5+DQN6bw=
#   on:
#     branch: master    
# #  on:
# #    tags: true
#   file: /io/wheelhouse/*
#   skip_cleanup: true
#   overwrite: true
#   python: 3.5
