name = "richdem"
uuid = "db566695-6f60-45f3-9b37-d3ff769e9aca"
authors = ["Sunayana Ghosh <sunayana@cervest.earth>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
